basePath: /
info:
  contact:
    email: Baye_Serigne.SECK@etu.uca.fr
    name: Baye serigne Seck.
  description: API to manage resource and alert.
  title: middleware/project
  version: 1.0.0
paths:
  /resources:
    get:
      consumes:
      - application/json
      description: Récupère la liste de toutes les ressources disponibles
      produces:
      - application/json
      responses:
        "500":
          description: Internal server error
          schema:
            type: string
      summary: Liste toutes les ressources
      tags:
      - Ressources
    post:
      consumes:
      - application/json
      description: Crée une nouvelle ressource avec un nom et un identifiant UCA
      produces:
      - application/json
      responses:
        "400":
          description: Invalid input
          schema:
            type: string
        "500":
          description: Internal server error
          schema:
            type: string
      summary: Crée une ressource
      tags:
      - Ressources
  /resources/{id}:
    delete:
      consumes:
      - application/json
      description: Supprime une ressource via son ID
      parameters:
      - description: ID de la ressource
        in: query
        name: id
        required: true
        type: string
      produces:
      - application/json
      responses:
        "204":
          description: Resource deleted successfully
          schema:
            type: string
        "400":
          description: Invalid ID
          schema:
            type: string
        "500":
          description: Internal server error
          schema:
            type: string
      summary: Supprime une ressource
      tags:
      - Ressources
    put:
      consumes:
      - application/json
      description: Met à jour une ressource via son ID
      parameters:
      - description: ID de la ressource
        in: query
        name: id
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: Resource updated successfully
          schema:
            type: string
        "400":
          description: Invalid input
          schema:
            type: string
        "500":
          description: Internal server error
          schema:
            type: string
      summary: Met à jour une ressource
      tags:
      - Ressources
schemes:
- http
swagger: "2.0"
